### ISSUE TITLE
提高代码可读性

### ISSUE THREAD

**Issue by 1751634419** [RESBI/Game-of-life#1]
你的代码中有一些可读性较低的语句。
1.  在每个符号后插入空格
	在你的C语言源码中，有一行是这样写的： 
        > for(int k = 3; k < W; k=k+6){  //Generate many flight.

       我绝不建议你这样书写你的代码，尽管它们看起来十分紧凑。我建议你这样写：
        > for (int k = 3; k < W; k=k+6) {  //Generate many flight.

**Comment by RESBI** [comment]
Thanks for your advice!

**Comment by 1751634419** [comment]
Good job!
